version: '3.9'

services:
  traefik:
    image: traefik:v2.9
    command: --api.insecure=true --providers.docker
    ports:
      - "8089:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  api:
    image: bansikah/random-group-generator:1.0
    container_name: random-group-generator
    ports:
      - "8082:8082"
    labels:
      - "traefik.http.routers.api.rule=Host(`banana.localhost`)"
    depends_on:
      - traefik

  quiz-app-spring-boot:
    image: bansikah/quiz-app-spring-boot:v1.0
    container_name: quiz-app-spring-boot
    ports:
      - "8084:8084"
    labels:
      - "traefik.http.routers.quiz-app-spring-boot.rule=Host(`quiz-app-spring-boot.localhost`)"
    depends_on:
      - traefik

  k8s-fast-api:
    image: bansikah/k8s-fast-api:1.0
    container_name: k8s-fast-api
    ports:
      - "8086:8086"
    labels:
      - "traefik.http.k8s-fast-api.rule=Host(`k8s-fast-api.localhost`)"
    depends_on:
      - traefik
