version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # Expose port 80 of the Nginx container
    volumes:
      - /home/adorsys/Desktop/dev/personal-projects/k8s-tuts/k8s-demo/reverse-proxy/3_example/nginx.conf:/etc/nginx/nginx.conf:ro  # Read-only mount for configuration
    depends_on:
      - random-group-generator
      - quiz-app-spring-boot
      - k8s-fast-api  # Ensure Nginx starts after applications

  random-group-generator:
    image: bansikah/random-group-generator:1.0
    container_name: random-group-generator

  quiz-app-spring-boot:
    image: bansikah/quiz-app-spring-boot:v1.0
    container_name: quiz-app-spring-boot

  k8s-fast-api:
    image: bansikah/k8s-fast-api:1.0
    container_name: k8s-fast-api
